export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export PATH="$PATH:$HOME/.dotnet/tools"
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"
COMPLETION_WAITING_DOTS="true"

plugins=(git
         httpie
         poetry
         docker
         vi-mode
         fzf
         zsh-autosuggestions
         zsh-syntax-highlighting
         asdf)

source $ZSH/oh-my-zsh.sh

# User configuration

export EDITOR='nvim'
export PAGER='less'
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# resolve dyld crash
export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib:$DYLD_LIBRARY_PATH


# vi mode
bindkey -v
export KEYTIMEOUT=1

autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

autoload -U bashcompinit
bashcompinit

eval "$(register-python-argcomplete pipx)"
complete -F __start_kubectl kc

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
